controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /home
    controller: App\Controller\HomeController::index

product:
    path: /product
    controller: App\Controller\ProductController::index

cart:
    path: /cart
    controller: App\Controller\CartController::index

product_details:
    path: /product/{name}
    controller: App\Controller\ProductController::details

tools:
    path: /tools
    controller: App\Controller\ToolsController::index

adminProduct:
    path: /adminProduct
    controller: App\Controller\ProductController::adminIndex

adminCategory:
    path: /adminCategory
    controller: App\Controller\CategoryController::adminIndex

adminUser:
    path: /adminUser
    controller: App\Controller\UserController::index

profile:
    path: /profile
    controller: App\Controller\ProfileController::index

account:
    path: /account
    controller: App\Controller\AccountController::index

payement:
    path: /payement
    controller: App\Controller\PayementController::index


checkout:
    path: /checkout
    controller: App\Controller\checkoutController::index

login:
    path: /login
    controller: App\Controller\LoginController::index

register:
    path: /register
    controller: App\Controller\RegisterController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index